// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUywMXyx300NlCNbRaoTPUHUy1byzHZxk',
    appId: '1:151024075058:web:0e997658282d266144972b',
    messagingSenderId: '151024075058',
    projectId: 'squat-bb102',
    authDomain: 'squat-bb102.firebaseapp.com',
    storageBucket: 'squat-bb102.appspot.com',
    measurementId: 'G-QF5W0SW9SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTgg2cMSEQU8V0PoDj6YFpTNFYeB_wlEg',
    appId: '1:151024075058:android:c87fb2d0ed92c81444972b',
    messagingSenderId: '151024075058',
    projectId: 'squat-bb102',
    storageBucket: 'squat-bb102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3qVciWk1ZC0N3dPnETK5SsYO4cBFrUY',
    appId: '1:151024075058:ios:e7e52e66fe21b47644972b',
    messagingSenderId: '151024075058',
    projectId: 'squat-bb102',
    storageBucket: 'squat-bb102.appspot.com',
    iosBundleId: 'com.relate.laatte',
  );
}
